[package]
name = "picker"
version = "0.1.0"
authors = [ "james.forcier@coreos.com" ]

[lib]
name = "picker"
crate-type = ["dylib"]
path = "src/picker.rs"

[dependencies]
uefi = { git = "https://github.com/csssuf/rust-uefi" }
rlibc = "1.0"
bitfield = "0.12.0"
